### ISSUE TITLE
When anon refreshes page what happens?

### ISSUE THREAD

**Issue by webmasterkai** [OOKB/delanyandlong#73]
What's the expected behavior when an anonymous user refreshes the page? Do we need to save and reload the user state? Mostly wondering about favs. Do they get lost or...

**Comment by bjornmeansbear** [comment]
Good question.

Optimally, yeah, it would be nice to have favs be saved. Sometimes the refresh isn't intentional, and it would be annoying to have been working and have them go away?

Remembering what list style you have active on the collection, or a certain search or similar would be nice, but isn't imperative.

**Comment by webmasterkai** [comment]
I've had it working before. Hopefully it's a lot of copypasta to make it work again.

**Comment by bjornmeansbear** [comment]
We think this is done 😄
